# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c94c7f775d71d6104432f43b1fe950554c54589e0926a9f4f08d5eaa091e66a7d824e80e52090d100f1e13e17ce5838a4a0a4f16e1705b557fb293ce4c17e8f8

test:
  secret_key_base: 23df7bacb346992fe06f361c2bd4119299ea309e782462b4d76ca294ded1451cb54162421410ee86ad20f3e5a3c2db89661666629a70b2d16e75e6ed478aa07a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
